export const data = [
    {
        name:"backblaze",
        minPrice:7,
        storage:0.005,
        transfer:0.01
    },
    {
        name:"bunny",
        minPrice:0,
        max:10,
        storage:{
            HDD:0.01,
            SSD:0.02
        },
        transfer:0.01
    },
    {
        name:"scaleway",
        minPrice:0,
        storage:{
            Multi:0.06,
            Single:0.03
        },
        transfer:0.02,
        free:75
    },
    {
        name:"vultr",
        minPrice:5,
        storage:0.01,
        transfer:0.01
    }
]